#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
      - '.gitignore'
  schedule:
    - cron: 0 */12 * * *
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: è®¾ç½®Githubè´¦æˆ·
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: åŒæ­¥ä¸Šæ¸¸
      run: |
        # åˆ é™¤gitç¼“å­˜ä»¥åŠé™¤äº†patchä»¥å¤–çš„æ–‡ä»¶å¤¹
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "patch"` >/dev/null 2>&1

        #miniupnpdæ”¯æŒå¼ºè¡Œæ˜ å°„
        svn export https://github.com/hzyitc/miniupnpd-openwrt-ptpt52-mod/trunk/miniupnpd

        #uuæ¸¸æˆåŠ é€Ÿå™¨
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-uugamebooster
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/uugamebooster
        
    - name: è§£å†³å†²çª
      run: |
        sed -i \
          -e 's?include \.\./\.\./\(lang\|devel\)?include $(TOPDIR)/feeds/packages/\1?' \
          -e "s/\(PKG_HASH\|PKG_MD5SUM\|PKG_MIRROR_HASH\):=.*/\1:=skip/" \
          -e 's?\.\./\.\./luci.mk?$(TOPDIR)/feeds/luci/luci.mk?' \
          -e 's/ca-certificates/ca-bundle/' \
          */Makefile
          
    - name: æäº¤
      run: |
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"

        # æ ¹æ®æ›´æ”¹æ¬¡æ•°ä¿®æ”¹Makefileçš„PKG_RELEASE
        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count master $pkg)/" $pkg/Makefile || true
          fi
        done

        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f

    - name: åˆ é™¤å†å²Actionè®°å½•
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3