#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Merge-upstream
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/upstream.yml'
      - '.gitignore'
  schedule:
    - cron: 0 0 * * *

jobs:
  merge:
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: è®¾ç½®Githubè´¦æˆ·
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: åŒæ­¥ä¸Šæ¸¸
      run: |
        
        # åˆ é™¤gitç¼“å­˜ä»¥åŠfeedsçš„æ–‡ä»¶å¤¹
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf ./feeds >/dev/null 2>&1
        mkdir feeds && cd feeds

        #luci-app-xray
        git clone --depth 1 https://github.com/yichya/luci-app-xray

        # uuæ¸¸æˆåŠ é€Ÿå™¨
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-uugamebooster
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/uugamebooster

        # vlmcsd
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-vlmcsd 
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/vlmcsd
        
        # ssr-plus
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-ssr-plus
        
        # passwall
        svn export https://github.com/Chikage0o0/openwrt-passwall/branches/luci/luci-app-passwall

        # passwall2
        svn export https://github.com/Chikage0o0/openwrt-passwall2/trunk/luci-app-passwall2

        # openclash
        svn export https://github.com/vernesong/OpenClash/trunk/luci-app-openclash
        #svn export https://github.com/vernesong/OpenClash/tags/v0.44.42-beta/luci-app-openclash

        # passwallä»¥åŠssr-plusçš„ä¾èµ–
        git clone --depth 1 -b packages https://github.com/Chikage0o0/openwrt-passwall
        rm -rf openwrt-passwall/v2ray-geodata
        rm -rf openwrt-passwall/sing-box
        mv -n `find openwrt-passwall/* -maxdepth 0 -type d` ./ && rm -rf openwrt-passwall
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/redsocks2
        git clone --depth 1 https://github.com/sbwml/v2ray-geodata

        # è¿…é›·å¿«é¸Ÿ
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-xlnetacc

        # mosdns
        svn export https://github.com/sbwml/luci-app-mosdns/trunk/luci-app-mosdns
        svn export https://github.com/sbwml/luci-app-mosdns/trunk/mosdns
        
        # sing-box
        svn export https://github.com/Chikage0o0/sing-box_openwrt/trunk/sing-box

        # ä¸»é¢˜
        svn export https://github.com/jerrykuku/luci-theme-argon/trunk ./luci-theme-argon
        svn export https://github.com/jerrykuku/luci-app-argon-config/trunk ./luci-app-argon-config
        # svn export https://github.com/thinktip/luci-theme-neobird/trunk ./luci-theme-neobird ä¸æ”¯æŒOpenwrtæœ€æ–°ç‰ˆ
        # svn export https://github.com/Chikage0o0/luci-theme-infinityfreedom/trunk/luci-theme-infinityfreedom ä¸æ”¯æŒOpenwrtæœ€æ–°ç‰ˆ

        # çµç¼‡åŠ é€Ÿå™¨
        git clone --depth 1 https://github.com/esirplayground/LingTiGameAcc
        git clone --depth 1 https://github.com/esirplayground/luci-app-LingTiGameAcc

        # diskman
        svn export https://github.com/lisaac/luci-app-diskman/trunk/applications/luci-app-diskman

        # Luci-app-socat
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-socat

        # Zerotierçš„é¢æ¿
        git clone --depth 1 https://github.com/rufengsuixing/luci-app-zerotier
        
        # Realtek 8125 é©±åŠ¨
        svn export https://github.com/csrutil/OpenWrt-NIC-Drivers/trunk/drivers/r8125

        # luci-app-nat6-helper
        git clone --depth 1 https://github.com/Ausaci/luci-app-nat6-helper

        # ç½‘æ˜“äº‘éŸ³ä¹è§£é”
        svn export https://github.com/maxlicheng/luci-app-unblockmusic/trunk/app luci-app-unblockmusic
        svn export https://github.com/maxlicheng/luci-app-unblockmusic/trunk/UnblockNeteaseMusicGo
        #svn export https://github.com/maxlicheng/luci-app-unblockmusic/trunk/UnblockNeteaseMusic

        # é«˜çº§è®¾ç½®
        git clone --depth 1 https://github.com/sirpdboy/luci-app-advanced

        # é˜¿é‡Œäº‘webdav
        svn export https://github.com/messense/aliyundrive-webdav/trunk/openwrt/luci-app-aliyundrive-webdav
        svn export https://github.com/messense/aliyundrive-webdav/trunk/openwrt/aliyundrive-webdav

        # koolproxyå»å¹¿å‘Š
        git clone --depth 1 https://github.com/yaof2/luci-app-ikoolproxy
        
    - name: åˆ é™¤å¤šä½™æ–‡ä»¶
      run: |
        rm -rf ./feeds/.svn
        rm -rf ./feeds/*/.git
        rm -rf ./feeds/*/.github
        rm -rf ./feeds/*/.svn
        rm -rf ./feeds/*/README.md
        rm -rf ./feeds/*/LICENSE

    - name: è§£å†³å†²çª
      run: |
        sed -i 's#../../luci.mk#$(TOPDIR)/feeds/luci/luci.mk#g' ./feeds/*/Makefile
          
    - name: æäº¤
      run: |
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f

    - name: è§¦å‘ç¼–è¯‘
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.SECRET_TOKEN }}
        event-type: Compile-IPK

    - name: åˆ é™¤å†å²Actionè®°å½•
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
