#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
      - '.gitignore'
  schedule:
    - cron: 0 */12 * * *
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: è®¾ç½®Githubè´¦æˆ·
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: åŒæ­¥ä¸Šæ¸¸
      run: |
        # åˆ é™¤gitç¼“å­˜ä»¥åŠé™¤äº†patchä»¥å¤–çš„æ–‡ä»¶å¤¹
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "patch"` >/dev/null 2>&1

        # miniupnpdæ”¯æŒå¼ºè¡Œæ˜ å°„
        svn export https://github.com/hzyitc/miniupnpd-openwrt-ptpt52-mod/trunk/miniupnpd

        # uuæ¸¸æˆåŠ é€Ÿå™¨
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-uugamebooster
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/uugamebooster

        # vlmcsd
        svn export https://github.com/siwind/luci-app-vlmcsd/trunk ./luci-app-vlmcsd
        svn export https://github.com/siwind/openwrt-vlmcsd/trunk ./openwrt-vlmcsd

        # ssr-plus
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-ssr-plus
        
        # passwall
        svn export https://github.com/xiaorouji/openwrt-passwall/branches/luci/luci-app-passwall

        # passwallä»¥åŠssr-plusçš„ä¾èµ–
        git clone --depth 1 -b packages https://github.com/xiaorouji/openwrt-passwall
        mv -n `find openwrt-passwall/* -maxdepth 0 -type d` ./ && rm -rf openwrt-passwall
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/redsocks2


    - name: åˆ é™¤å¤šä½™æ–‡ä»¶
      run: |
        rm -rf .svn
        rm -rf ./*/.git
        rm -rf ./*/.github
        rm -rf ./*/.svn 
        rm -f .gitattributes .gitignore
        rm -f README.md

    - name: è§£å†³å†²çª
      run: |
        sed -i 's#../../luci.mk#$(TOPDIR)/feeds/luci/luci.mk#g' */Makefile
          
    - name: æäº¤
      run: |
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f

    - name: åˆ é™¤å†å²Actionè®°å½•
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3